- name: Deploy Nagios 
  become: true
  hosts: masterserver
  roles:
  - role: nagios_plugins
  - role: nagios_core

- name: Deploy NRPE
  become: true
  hosts: clientservers
  roles:
  - role: nagios_plugins
  - role: nagios_nrpe