---

- name: Nagios Plugin Installation on RHEL8
  include: rhel.yml
  when: ansible_os_family == 'RedHat'

- name: Nagios Plugin Installation on Ubuntu
  include: ubuntu.yml
  when: ansible_os_family == 'Debian' 