---
# vars file for nagios_plugins
ubuntu_prerequisites:
  - autoconf 
  - build-essential
  - gcc
  - libc6
  - libmcrypt-dev
  - make
  - libssl-dev
  - wget
  - bc
  - gawk
  - dc
  - snmp
  - libnet-snmp-perl
  - gettext
