---
# tasks file for nagios_plugins
- name: Download and unarchieve the nagios plugins from source
  unarchive:
    src: "{{ nagios_plugin_download_source_link }}/release-{{ nagios_plugin_version }}.tar.gz"
    dest: "{{ plugin_download_dir }}"
    remote_src: yes

- name: Set tools setup
  become: true
  command: ./tools/setup
  args:
    chdir: "{{ plugin_download_dir }}/{{ nagios_plugin_download_file }}"

- name: Configure
  become: true
  command: ./configure
  args:
    chdir: "{{ plugin_download_dir }}/{{ nagios_plugin_download_file }}"

- name: Make
  become: true
  command: make
  args:
    chdir: "{{ plugin_download_dir }}/{{ nagios_plugin_download_file }}"

- name: Make Install
  become: true
  command: make install
  args:
    chdir: "{{ plugin_download_dir }}/{{ nagios_plugin_download_file }}"