galaxy_info:
  author: Nithin C Bandi
  description: Role to install and Configure NRPE on RHEL and Ubuntu client machines

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.9
  
  platforms:
  - name: RHEL
    versions:
    - 8
  - name: Ubuntu
    versions:
    - 18.04
  
  galaxy_tags:
    - monitoring
    - nagios
    - nrpe
    - nagios-plugins